### ISSUE TITLE
Getting OverlappingFileLockException.

### ISSUE THREAD

**Issue by bardam** [davidB/scala-maven-plugin#163]
I get the following exception when running the plugin in my CI server,
I have zinc installed on the machine.
It seems that the plugin checks the scala version which leads to this exception.
The maven build runs in several threads.

```
[08:16:59]W:     [Step 2/3] [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:testCompile (scala-test-compile) on project Amelia: Execution scala-test-compile of goal net.alchim31.maven:scala-maven-plugin:3.1.6:testCompile failed. OverlappingFileLockException -> [Help 1]
[08:16:59] :     [Step 2/3] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:testCompile (scala-test-compile) on project Amelia: Execution scala-test-compile of goal net.alchim31.maven:scala-maven-plugin:3.1.6:testCompile failed.
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
[08:16:59] :     [Step 2/3]     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[08:16:59] :     [Step 2/3]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[08:16:59] :     [Step 2/3]     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[08:16:59] :     [Step 2/3]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[08:16:59] :     [Step 2/3]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[08:16:59] :     [Step 2/3]     at java.lang.Thread.run(Thread.java:745)
[08:16:59] :     [Step 2/3] Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-test-compile of goal net.alchim31.maven:scala-maven-plugin:3.1.6:testCompile failed.
[08:16:59] :     [Step 2/3]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
[08:16:59] :     [Step 2/3]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[08:16:59] :     [Step 2/3]     ... 11 more
[08:16:59] :     [Step 2/3] Caused by: java.nio.channels.OverlappingFileLockException
[08:16:59] :     [Step 2/3]     at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
[08:16:59] :     [Step 2/3]     at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
[08:16:59] :     [Step 2/3]     at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1011)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.read(DefaultUpdateCheckManager.java:370)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.readLastUpdated(DefaultUpdateCheckManager.java:322)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.readLastUpdated(DefaultUpdateCheckManager.java:158)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.isUpdateRequired(DefaultUpdateCheckManager.java:147)
[08:16:59] :     [Step 2/3]     at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:121)
[08:16:59] :     [Step 2/3]     at org.apache.maven.project.artifact.MavenMetadataSource.retrieveAvailableVersions(MavenMetadataSource.java:436)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:497)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:584)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:144)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:100)
[08:16:59] :     [Step 2/3]     at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:782)
[08:16:59] :     [Step 2/3]     at org.apache.maven.shared.dependency.tree.DefaultDependencyTreeBuilder.buildDependencyTree(DefaultDependencyTreeBuilder.java:97)
[08:16:59] :     [Step 2/3]     at scala_maven.ScalaMojoSupport.checkCorrectVersionsOfScalaLibrary(ScalaMojoSupport.java:586)
[08:16:59] :     [Step 2/3]     at scala_maven.ScalaMojoSupport.checkScalaVersion(ScalaMojoSupport.java:566)
[08:16:59] :     [Step 2/3]     at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:481)
[08:16:59] :     [Step 2/3]     at scala_maven.ScalaTestCompileMojo.execute(ScalaTestCompileMojo.java:48)
[08:16:59] :     [Step 2/3]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[08:16:59] :     [Step 2/3]     ... 12 more
```

**Comment by davidB** [comment]
I'm not a Zinc user, but Zinc seems to lock files, so it can't run in concurrent Thread.

**Comment by slandelle** [comment]
Zinc server support has been dropped, see #299.
Closing.
