### ISSUE TITLE
Scala Mixed Java Scala project problem

### ISSUE THREAD

**Issue by danyaljj** [davidB/scala-maven-plugin#170]
I followed this: 
http://davidb.github.io/scala-maven-plugin/example_java.html
and created a sample project:
https://github.com/danyaljj/sampleMixedScalaJavaMavenProject
I keep getting the following error. Where am I going wrong? 
```
AI2s-MBP-7:mixedScalaJavaProject i-danielk$ mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Test for Java + Scala compilation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testJavaAndScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.1:add-source (scala-compile-first) @ testJavaAndScala ---
[INFO] Add Source directory: /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/scala
[INFO] Add Test Source directory: /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.1:compile (scala-compile-first) @ testJavaAndScala ---
[INFO] /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/java:-1: info: compiling
[INFO] /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/scala:-1: info: compiling
[INFO] Compiling 2 source files to /Users/i-danielk/ideaProjects/mixedScalaJavaProject/target/classes at 1440462398489
[ERROR] error: error while loading Consumer, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar(java/util/function/Consumer.class)' is broken
[INFO] (bad constant pool tag 18 at byte 15)
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.366 s
[INFO] Finished at: 2015-08-24T19:26:39-05:00
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.1:compile (scala-compile-first) on project testJavaAndScala: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
AI2s-MBP-7:mixedScalaJavaProject i-danielk$ 
```

**Comment by danyaljj** [comment]
And more verbose: 

```
AI2s-MBP-7:mixedScalaJavaProject i-danielk$ mvn compile -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Test for Java + Scala compilation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testJavaAndScala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.1:add-source (scala-compile-first) @ testJavaAndScala ---
[INFO] Add Source directory: /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/scala
[INFO] Add Test Source directory: /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.1:compile (scala-compile-first) @ testJavaAndScala ---
[INFO] /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/java:-1: info: compiling
[INFO] /Users/i-danielk/ideaProjects/mixedScalaJavaProject/src/main/scala:-1: info: compiling
[INFO] Compiling 2 source files to /Users/i-danielk/ideaProjects/mixedScalaJavaProject/target/classes at 1440462789050
[ERROR] error: error while loading Consumer, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar(java/util/function/Consumer.class)' is broken
[INFO] (bad constant pool tag 18 at byte 15)
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.366 s
[INFO] Finished at: 2015-08-24T19:33:09-05:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.1:compile (scala-compile-first) on project testJavaAndScala: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.1:compile (scala-compile-first) on project testJavaAndScala: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:490)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at scala_maven_executions.JavaMainCallerByFork.run(JavaMainCallerByFork.java:100)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:161)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by davidB** [comment]
What is the version of scala ? (I guess the java version is 1.8.0_45)

**Comment by danyaljj** [comment]
Whoops ... I got it to work after I msged here, but forgot to close this. Closing now ...

**Comment by ericdgonzalez** [comment]
Hi I'm having a similar problem. Could you please provide the work around you used if you still remember?

**Comment by danyaljj** [comment]
This might help? https://github.com/danyaljj/sampleMixedScalaJavaMavenProject

**Comment by Jacktavitt** [comment]
I checked to make sure the Scala and Spark versions in mine were correct. When I changed the Spark version to the correct one, the problem was resolved.
