### ISSUE TITLE
hello world failed when use scala 2.11

### ISSUE THREAD

**Issue by cnglen** [davidB/scala-maven-plugin#199]
**For scala 2.10, OK.**
`  <properties>
    <scala.version>2.10.5</scala.version>
    <scala.compat.version>2.10</scala.compat.version>
  </properties>
`
  
For scala 2.11, **error occurs.** 
`<properties>
    <scala.version>2.11.5</scala.version>
    <scala.compat.version>2.11</scala.compat.version>
  </properties>
`

**Log of error:**

2017-01-11 11:11:54.735 [INFO] BUILD FAILURE
2017-01-11 11:11:54.735 [INFO] ------------------------------------------------------------------------
2017-01-11 11:11:54.735 [INFO] Total time: 6.294 s
2017-01-11 11:11:54.736 [INFO] Finished at: 2017-01-11T11:11:54+08:00
2017-01-11 11:11:54.884 [INFO] Final Memory: 27M/503M
2017-01-11 11:11:54.884 [INFO] ------------------------------------------------------------------------
2017-01-11 11:11:54.885 [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (default) on project scope_confirmor: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (default) on project scope_confirmor: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:490)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at scala_maven_executions.JavaMainCallerByFork.run(JavaMainCallerByFork.java:100)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:161)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	... 22 more
2017-01-11 11:11:54.886 [ERROR] 
2017-01-11 11:11:54.886 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2017-01-11 11:11:54.886 [ERROR] 
2017-01-11 11:11:54.886 [ERROR] For more information about the errors and possible solutions, please read the following articles:
2017-01-11 11:11:54.886 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lefou** [comment]
@cnglen, you might want to post a bit more info to reproduce this issue, e.g. at least your `pom.xml`.

**Comment by slandelle** [comment]
Idle without any info from user for a long time. Closing.
