### ISSUE TITLE
Scala 2.12.4 support

### ISSUE THREAD

**Issue by acumartini** [davidB/scala-maven-plugin#230]
When I try to compile a project with scala 2.12.4 and Java 8:

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:compile (default) on project black-marlin-processors-core: wrap: java.lang.reflect.InvocationTargetException: ExceptionInInitializerError: Not a version: 9 -> [Help 1]
```

And when I run the `scala-maven-plugin` integ-test build locally with the scala version set to 2.12.4 I see the following:

```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Building Test for Java + Scala compilation with too many files and non-forked execution 1.0-SNAPSHOT
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO]
[INFO] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testLotsofJavaFiles ---
[INFO] [INFO] Deleting /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/target
[INFO] [INFO]
[INFO] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testLotsofJavaFiles ---
[INFO] [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] [INFO] skip non existing resourceDirectory /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/src/main/resources
[INFO] [INFO]
[INFO] [INFO] --- scala-maven-plugin:3.3.2-SNAPSHOT:add-source (scala-compile-first) @ testLotsofJavaFiles ---
[INFO] [INFO] Add Source directory: /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/src/main/scala
[INFO] [INFO] Add Test Source directory: /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/src/test/scala
[INFO] [INFO]
[INFO] [INFO] --- scala-maven-plugin:3.3.2-SNAPSHOT:compile (scala-compile-first) @ testLotsofJavaFiles ---
[INFO] [INFO] /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/src/main/java:-1: info: compiling
[INFO] [INFO] /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/src/main/scala:-1: info: compiling
[INFO] [INFO] Compiling 514 source files to /Users/ama112/git/scala-maven-plugin/target/it/testLotsofJavaFiles/target/classes at 1517260608759
[INFO] [INFO] java.lang.reflect.InvocationTargetException
[INFO] [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] [INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] [INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] [INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] [INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] [ERROR] Caused by: java.lang.ExceptionInInitializerError
[INFO] [INFO] 	at scala.tools.nsc.util.package$.<init>(package.scala:127)
[INFO] [INFO] 	at scala.tools.nsc.util.package$.<clinit>(package.scala)
[INFO] [INFO] 	at scala.tools.nsc.Global.throwableAsString(Global.scala:326)
[INFO] [INFO] 	at scala.tools.nsc.Global.reportThrowable(Global.scala:325)
[INFO] [INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:58)
[INFO] [INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[INFO] [INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] [INFO] 	... 6 more
[INFO] [INFO] Caused by: java.lang.NumberFormatException: Not a version: 9
[INFO] [INFO] 	at scala.util.PropertiesTrait.parts$1(Properties.scala:186)
[INFO] [INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast(Properties.scala:189)
[INFO] [INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast$(Properties.scala:183)
[INFO] [INFO] 	at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
[INFO] [INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<init>(ScalaClassLoader.scala:157)
[INFO] [INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<clinit>(ScalaClassLoader.scala)
[INFO] [INFO] 	... 13 more
```

**Comment by acumartini** [comment]
Been working on debugging this... It appears to be hitting the scala `2.10.6` version of `isJavaAtLeast` from `2.12.4` call.

```
def isJavaAtLeast(version: String): Boolean = {
    def parts(x: String) = {
      val i = x.indexOf('.')
      if (i < 0) throw new NumberFormatException("Not a version: " + x)
      (x.substring(0, i), x.substring(i+1, x.length))
    }
    val (v, _v) = parts(version)
    val (s, _s) = parts(javaSpecVersion)
    s.toInt >= v.toInt && _s.toInt >= _v.toInt
  }```

**Comment by acumartini** [comment]
Looks like fixing this bug required an overhaul to the new zinc compiler.

**Comment by davidB** [comment]
The new zinc compiler will not be integrated in this plugin (until PR)
You can take a look at https://github.com/random-maven/scalor-maven-plugin (works with zinc 1.x)

**Comment by jozic** [comment]
@davidB so what is a workaround for using this plugin and scala >= 2.12.4?
Or there's no one?

**Comment by davidB** [comment]
@jozic I ran successfully integration-test of scala-maven-plugin with scala 2.12.6.

**Comment by jozic** [comment]
could you please share your scala-maven-plugin configuration?
I've tried 2.12.6 and got aforementioned `java.lang.NumberFormatException: Not a version: 9`

here's my config (well, part which is relevant I believe)

```scala
    <properties>
        <java.version>1.8</java.version>
        <scala.version>2.12.6</scala.version>
        <scala.binary.version>2.12</scala.binary.version>
    </properties>

    <build>
        <plugins>
                <plugin>
                    <groupId>net.alchim31.maven</groupId>
                    <artifactId>scala-maven-plugin</artifactId>
                    <version>3.3.2</version>
                    <configuration>
                        <scalaCompatVersion>${scala.binary.version}</scalaCompatVersion>
                        <scalaVersion>${scala.version}</scalaVersion>
                        <args>
                            <arg>-Xlint</arg>
                            <arg>-deprecation</arg>
                            <arg>-unchecked</arg>
                            <arg>-feature</arg>
                            <arg>-language:postfixOps</arg>
                            <arg>-language:implicitConversions</arg>
                            <arg>-language:higherKinds</arg>
                            <arg>-Xfatal-warnings</arg>
                            <arg>-Ywarn-unused</arg>
                            <arg>-Ywarn-unused-import</arg>
                            <arg>-Ywarn-inaccessible</arg>
                            <arg>-Ywarn-dead-code</arg>
                            <arg>-Ypartial-unification</arg>
                        </args>
                        <jvmArgs>
                            <jvmArg>-Xmx4g</jvmArg>
                        </jvmArgs>
                    </configuration>
                    <executions>
                        <execution>
                            <id>scala-compile-first</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>add-source</goal>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>scala-test-compile</id>
                            <phase>process-test-resources</phase>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
         </plugins>
    </build>
```
it works fine with `2.12.3`

I appreciate your time, thanks!

**Comment by davidB** [comment]
Previously, I just run the integration-test of the scala-maven-plugin (see last commit): 
- jdk 1.8, scala-maven-plugin 3.4.2-SNAPSHOT (same as 3.4.1), scala version 2.12.6 for integration test
- ./mvnw clean integration-test

I just create a simple project from the scala-maven-archetype 1.7, and by default it used:
- scala 2.12.6
- scala-maven-plugin 3.3.2 (like you)

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>archetype.it</groupId>
  <artifactId>basic-project</artifactId>
  <version>0.1-SNAPSHOT</version>
  <name>${project.artifactId}</name>
  <description>My wonderfull scala app</description>
  <inceptionYear>2018</inceptionYear>
  <licenses>
    <license>
      <name>My License</name>
      <url>http://....</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <encoding>UTF-8</encoding>
    <scala.version>2.12.6</scala.version>
    <scala.compat.version>2.12</scala.compat.version>
    <spec2.version>4.2.0</spec2.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest_${scala.compat.version}</artifactId>
      <version>3.0.5</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.specs2</groupId>
      <artifactId>specs2-core_${scala.compat.version}</artifactId>
      <version>${spec2.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.specs2</groupId>
      <artifactId>specs2-junit_${scala.compat.version}</artifactId>
      <version>${spec2.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/scala</sourceDirectory>
    <testSourceDirectory>src/test/scala</testSourceDirectory>
    <plugins>
      <plugin>
        <!-- see http://davidb.github.com/scala-maven-plugin -->
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.3.2</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <args>
                <arg>-dependencyfile</arg>
                <arg>${project.build.directory}/.scala_dependencies</arg>
              </args>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.21.0</version>
        <configuration>
          <!-- Tests will be run with scalatest-maven-plugin instead -->
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.scalatest</groupId>
        <artifactId>scalatest-maven-plugin</artifactId>
        <version>2.0.0</version>
        <configuration>
          <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
          <junitxml>.</junitxml>
          <filereports>TestSuiteReport.txt</filereports>
          <!-- Comma separated list of JUnit test class names to execute -->
          <jUnitClasses>samples.AppTest</jUnitClasses>
        </configuration>
        <executions>
          <execution>
            <id>test</id>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

Can you share the full stacktrace of the error ?
are you using jdk 8, 9 or 10 (regardless of the properties).

```
➜  basic-project git:(master) java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by jozic** [comment]
I believe I use jdk 8 and I don't even have 9 or 10 installed

```
➜  sand git:(...) ✗ update-alternatives --config java 
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-7-oracle/jre/bin/java          1082      auto mode
  1            /usr/lib/jvm/java-7-oracle/jre/bin/java          1082      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
* 3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 
```

```
➜  sand git:(...) ✗ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-116-generic", arch: "amd64", family: "unix"
➜
➜  sand git:(...) ✗ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
➜
➜  sand git:(...) ✗ mvn clean compile                                 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Sandwich
[INFO] sand-app
[INFO] sand-perf-test
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Sandwich 1.0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sand ---
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building sand-app 1.0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
...
[INFO] --- scala-maven-plugin:3.3.2:add-source (scala-compile-first) @ sand-app ---
[INFO] 
[INFO] --- scala-maven-plugin:3.3.2:compile (scala-compile-first) @ sand-app ---
[INFO] /home/eplatonov/projects/sand/sand-app/src/main/scala:-1: info: compiling
[INFO] Compiling 74 source files to /home/eplatonov/projects/sand/sand-app/target/classes at 1529306516871
[INFO] java.lang.reflect.InvocationTargetException
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.ExceptionInInitializerError
[INFO] 	at scala.tools.nsc.util.package$.<init>(package.scala:127)
[INFO] 	at scala.tools.nsc.util.package$.<clinit>(package.scala)
[INFO] 	at scala.tools.nsc.Global.throwableAsString(Global.scala:316)
[INFO] 	at scala.tools.nsc.Global.reportThrowable(Global.scala:315)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:58)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	... 6 more
[INFO] Caused by: java.lang.NumberFormatException: Not a version: 9
[INFO] 	at scala.util.PropertiesTrait.parts$1(Properties.scala:186)
[INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast(Properties.scala:189)
[INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast$(Properties.scala:183)
[INFO] 	at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
[INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<init>(ScalaClassLoader.scala:157)
[INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<clinit>(ScalaClassLoader.scala)
[INFO] 	... 13 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Sandwich ........................................... SUCCESS [  2.322 s]
[INFO] sand-app ........................................... FAILURE [ 10.309 s]
[INFO] sand-perf-test ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.513 s
[INFO] Finished at: 2018-06-18T03:21:57-04:00
[INFO] Final Memory: 65M/705M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.2:compile (scala-compile-first) on project sand-app: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sand-app
```


I also tried replacing my configuration section with yours
```
                    <executions>
                        <execution>
                            <goals>
                                <goal>compile</goal>
                                <goal>testCompile</goal>
                            </goals>
                        </execution>
                    </executions>
```
but no changes, same stacktrace

**Comment by davidB** [comment]
```
➜ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/davidb/bin/soft/apache-maven-3.3.3
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

Can you share a sample project that reproduce the issue ?
You can start from archetype, if you can not share your current project.
```
➜  mvn archetype:generate -B \
    -DarchetypeGroupId=net.alchim31.maven -DarchetypeArtifactId=scala-archetype-simple -DarchetypeVersion=1.7 \
    -DgroupId=com.company -DartifactId=sample2126 -Dversion=0.1.0-SNAPSHOT -Dpackage=com.company
...
➜  cd sample2126
➜  mvn test
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.367 s
[INFO] Finished at: 2018-06-18T20:44:05+02:00
[INFO] Final Memory: 15M/309M
[INFO] ------------------------------------------------------------------------
```

From a quick search in google, the cause of your problem could be
- java 9, see https://github.com/playframework/playframework/issues/7879
- or some dependencies (maybe compiled with jdk 9) see https://groups.google.com/forum/#!topic/gatling/ScipK91_mfw

**Comment by jozic** [comment]
I've tried the archetype (generated it using your command) and got same issue :(

```xml
➜  sample2126 mvn clean test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sample2126 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sample2126 ---
[INFO] Deleting /home/eplatonov/tmp/maven-scala-plugin-sandbox/sample2126/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample2126 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/eplatonov/tmp/maven-scala-plugin-sandbox/sample2126/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ sample2126 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.3.2:compile (default) @ sample2126 ---
[INFO] /home/eplatonov/tmp/maven-scala-plugin-sandbox/sample2126/src/main/scala:-1: info: compiling
[INFO] Compiling 1 source files to /home/eplatonov/tmp/maven-scala-plugin-sandbox/sample2126/target/classes at 1529350644419
[INFO] java.lang.reflect.InvocationTargetException
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.ExceptionInInitializerError
[INFO] 	at scala.tools.nsc.util.package$.<init>(package.scala:127)
[INFO] 	at scala.tools.nsc.util.package$.<clinit>(package.scala)
[INFO] 	at scala.tools.nsc.Global.throwableAsString(Global.scala:316)
[INFO] 	at scala.tools.nsc.Global.reportThrowable(Global.scala:315)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:58)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	... 6 more
[INFO] Caused by: java.lang.NumberFormatException: Not a version: 9
[INFO] 	at scala.util.PropertiesTrait.parts$1(Properties.scala:186)
[INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast(Properties.scala:189)
[INFO] 	at scala.util.PropertiesTrait.isJavaAtLeast$(Properties.scala:183)
[INFO] 	at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
[INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<init>(ScalaClassLoader.scala:157)
[INFO] 	at scala.reflect.internal.util.ScalaClassLoader$.<clinit>(ScalaClassLoader.scala)
[INFO] 	... 13 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.292 s
[INFO] Finished at: 2018-06-18T15:37:25-04:00
[INFO] Final Memory: 14M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.2:compile (default) on project sample2126: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I guess the main difference left is OS

**Comment by jozic** [comment]
funny enough, it does compiles with scala `2.12.4` and `2.12.5`, only `2.12.6` causes this error for me

**Comment by zhongqiangczq** [comment]
scala-maven-plugin version should compatible with scala version
