### ISSUE TITLE
Malformed class name error upon saving or running scala class

### ISSUE THREAD

**Issue by tenstriker** [davidB/scala-maven-plugin#259]
This issue happens with scala, maven project:

I am using eclipse Oxygen with scala ide 4.7

I suddenly started getting following error in pop ups when trying to run main method on scala object/class; Starts happening after adding class in same file as companion object.
"
Throwable during asyncExec
Malformed class name"

Next pop up after this tells me it is recommended to exit workbench. If I do it happens again upon restart of eclipse. 

Following is log file content. 

!ENTRY org.scala-ide.sdt.core 4 0 2018-03-21 13:03:33.805
!MESSAGE Throwable during asyncExec
!STACK 0
java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Class.java:1322)
        at java.lang.Class.isAnonymousClass(Class.java:1403)
        at org.scalaide.core.internal.logging.log4j.Log4JFacade$Logger$.apply(Log4JFacade.scala:60)
        at org.scalaide.core.internal.logging.log4j.Log4JFacade.getLogger(Log4JFacade.scala:68)
        at org.scalaide.logging.HasLogger.logger(HasLogger.scala:19)
        at org.scalaide.logging.HasLogger.logger$(HasLogger.scala:17)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector.logger$lzycompute(JUnit4TestClassesCollector.scala:17)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector.logger(JUnit4TestClassesCollector.scala:17)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector.getClassSafe(JUnit4TestClassesCollector.scala:82)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector.RunWithAnnotationOpt$lzycompute(JUnit4TestClassesCollector.scala:74)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector.RunWithAnnotationOpt(JUnit4TestClassesCollector.scala:74)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector$JUnit4TestClassesTraverser.hasRunWithAnnotation(JUnit4TestClassesCollector.scala:59)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector$JUnit4TestClassesTraverser.isTestClass(JUnit4TestClassesCollector.scala:57)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector$JUnit4TestClassesTraverser.$anonfun$isRunnableTestClass$1(JUnit4TestClassesCollector.scala:44)
        at org.scalaide.core.internal.launching.JUnit4TestClassesCollector$JUnit4TestClassesTraverser$$Lambda$2510/186495202.apply$mcZ$sp(Unknown Source)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
        at scala.tools.nsc.util.InterruptReq.execute(InterruptReq.scala:26)
        at scala.tools.nsc.interactive.Global.$anonfun$pollForWork$1(Global.scala:444)
        at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:418)
        at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22)

**Comment by davidB** [comment]
Can you reproduce the issue from command line (without eclipse) ? Or can you provide a reproductible project + setup ?

TBH, expect your comment about commenting the scala-maven-plugin I don't see from the log why it's an issue with the plugin. You should contact the eclipse scala-ide team.
