### ISSUE TITLE
Error in scala-maven-plugin: object scala not found

### ISSUE THREAD

**Issue by sachinlala** [davidB/scala-maven-plugin#281]
Please can you help with the below error ? I have tried various solutions but have hit the wall and nothing seems to work.

### Documentation referred
http://davidb.github.io/scala-maven-plugin/example_java.html

### Error stack
```[ERROR] error: error while loading <root>, zip file is empty
[ERROR] error: scala.tools.nsc.MissingRequirementError: object scala not found.
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.getModuleOrClass(Definitions.scala:655)
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.getModule(Definitions.scala:605)
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackage(Definitions.scala:145)
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackageClass(Definitions.scala:146)
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.AnyClass(Definitions.scala:176)
[INFO] 	at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:814)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:697)
[INFO] 	at scala.tools.nsc.Main$.process(Main.scala:105)
[INFO] 	at scala.tools.nsc.Main$.main(Main.scala:123)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```
```[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.3:compile (scala-compile-first) on project asda-feeds-ingestion: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1)```

### Versions
* scala-maven-plugin.version: 3.1.3
* scala.version: 2.9.2
* maven-compiler-plugin.version: 3.1
* maven-assembly-plugin.version: 3.1.0

### Relevant POM sections:
```
<dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
</dependency>
```
```
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>net.alchim31.maven</groupId>
          <artifactId>scala-maven-plugin</artifactId>
          <version>${scala-maven-plugin.version}</version>
          <configuration>
            <scalaVersion>${scala.version}</scalaVersion>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${maven-assembly-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
```
```
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <phase>compile</phase>
          </execution>
          <execution>
            <id>scala-compile-first</id>
            <phase>process-resources</phase>
            <goals>
              <goal>add-source</goal>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>scala-test-compile</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>${jdk.version}</source>
          <target>${jdk.version}</target>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>ScalaApplication</mainClass>
            </manifest>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

### About the Project
* I am building a Spring Boot based Java & Scala mix project, wherein a SpringBootApplication (Java based) invokes a RestController (Java based) which further invokes required Scala Class.
* The Java classes are in src/main/java path and Scala classes are in src/main/scala path.
* The issue started coming when I wrote a RestAssured based test.

**Comment by davidB** [comment]
If you start a new project:
1. use newer version of scala (eg 2.12.6) and newer version of the plugin (3.4.2)
2. there is some incompatibilities between recent java version 9+ and scala (eg #234 or search in non open issue)

**Comment by sachinlala** [comment]
The issue turns out to be due to a transitive dependency that was present in rest-assured library. Excluding the groovy dependency from rest-assured helped resolve the issue. My current build is with JDK 1.8.x.
Thanks for the prompt response @davidB. Will look into updating to latest version of the plugin as well.
