### ISSUE TITLE
Caused by: java.util.NoSuchElementException While mvn build

### ISSUE THREAD

**Issue by sauravomar** [davidB/scala-maven-plugin#399]
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /var/lib/jenkins/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.11-1.3.2-bin_2.11.7__52.0-1.3.2_20200115T025827.jar
[INFO] Compiler bridge file is not installed yet
[DEBUG] Using transporter WagonTransporter with priority -1.0 for http://artifactory.fkinternal.com/artifactory/v1.0/artifacts/libs-release-local
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for http://artifactory.fkinternal.com/artifactory/v1.0/artifacts/libs-release-local
Downloading: http://artifactory.fkinternal.com/artifactory/v1.0/artifacts/libs-release-local/org/scala-sbt/compiler-bridge_2.11/1.3.2/compiler-bridge_2.11-1.3.2-sources.jar
         
[DEBUG] Writing tracking file /var/lib/jenkins/.m2/repository/org/scala-sbt/compiler-bridge_2.11/1.3.2/compiler-bridge_2.11-1.3.2-sources.jar.lastUpdated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.256 s
[INFO] Finished at: 2020-04-28T14:15:11+00:00
[INFO] Final Memory: 62M/2149M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.1:compile (default) on project monopoly-fstream: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.3.1:compile failed. NoSuchElementException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.1:compile (default) on project monopoly-fstream: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.3.1:compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.3.1:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at scala_maven.MavenArtifactResolver.getJar(MavenArtifactResolver.java:22)
	at sbt_inc.SbtIncrementalCompiler.getCompiledBridgeJar(SbtIncrementalCompiler.java:219)
	at sbt_inc.SbtIncrementalCompiler.<init>(SbtIncrementalCompiler.java:79)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:287)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:109)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:91)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:555)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

**Comment by slandelle** [comment]
I'll be improving the error message, but it means you couldn't download this jar: `org.scala-sbt:compiler-bridge_2.11:1.3.2:sources`. 

As you can see [here](https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.11/1.3.2/), it's available on maven central.

The reason of the download failure is most likely your internal Artifactory server that you use to proxify public repositories.
Either it failed to download the artifact, or it refused to do so because it only contains artifacts that have been validated/authorized.

Anyway, the problem is on your side.
